export interface CaseSeed {
  slug: string
  name: string
  description: string
  imageUrl?: string
  casePrice: number
  keyPrice: number | null
  /** Skin slugs (see skins.ts) included in this case's drop table. */
  skinSlugs: string[]
}

// Generert fra ekte CS2-case-droptabeller (ByMykel/CSGO-API).
export const caseSeeds: CaseSeed[] = [
  {
    slug: 'danger-zone-case',
    name: 'Danger Zone Case',
    description: 'Ekte Danger Zone Case-lineup, hentet direkte fra CS2 sitt droptabell-arkiv.',
    imageUrl: 'https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGJKz2lu_XsnXwtmkJjSU91dh8bj35VTqVBP4io_fr3MVv_H4a6FucPPBWjDIkbdz4rg4Syyyxxsi5mzRntuvJCqVbwAgDZBwRPlK7EcZJ5GkQA',
    casePrice: 500,
    keyPrice: 100,
    skinSlugs: [
      'mp9-modest-threat',
      'glock-18-oxide-blaze',
      'nova-wood-fired',
      'm4a4-magnesium',
      'sawed-off-black-sand',
      'sg-553-danger-close',
      'tec-9-fubar',
      'g3sg1-scavenger',
      'galil-ar-signal',
      'mac-10-pipe-down',
      'p250-nevermore',
      'usp-s-flashback',
      'ump-45-momentum',
      'desert-eagle-mecha-industries',
      'mp5-sd-phosphor',
      'ak-47-asiimov',
      'awp-neo-noir',
      'navaja-knife',
      'navaja-knife-fade',
      'navaja-knife-crimson-web',
      'navaja-knife-slaughter',
      'navaja-knife-case-hardened',
      'navaja-knife-urban-masked',
      'navaja-knife-blue-steel',
      'navaja-knife-night-stripe',
      'navaja-knife-stained',
      'navaja-knife-forest-ddpat',
      'navaja-knife-boreal-forest',
      'navaja-knife-scorched',
      'navaja-knife-safari-mesh',
      'stiletto-knife',
      'stiletto-knife-fade',
      'stiletto-knife-crimson-web',
      'stiletto-knife-slaughter',
      'stiletto-knife-case-hardened',
      'stiletto-knife-urban-masked',
      'stiletto-knife-blue-steel',
      'stiletto-knife-night-stripe',
      'stiletto-knife-stained',
      'stiletto-knife-forest-ddpat',
      'stiletto-knife-boreal-forest',
      'stiletto-knife-scorched',
      'stiletto-knife-safari-mesh',
      'talon-knife',
      'talon-knife-fade',
      'talon-knife-crimson-web',
      'talon-knife-slaughter',
      'talon-knife-case-hardened',
      'talon-knife-urban-masked',
      'talon-knife-blue-steel',
      'talon-knife-night-stripe',
      'talon-knife-stained',
      'talon-knife-forest-ddpat',
      'talon-knife-boreal-forest',
      'talon-knife-scorched',
      'talon-knife-safari-mesh',
      'ursus-knife',
      'ursus-knife-fade',
      'ursus-knife-crimson-web',
      'ursus-knife-slaughter',
      'ursus-knife-case-hardened',
      'ursus-knife-urban-masked',
      'ursus-knife-blue-steel',
      'ursus-knife-night-stripe',
      'ursus-knife-stained',
      'ursus-knife-forest-ddpat',
      'ursus-knife-boreal-forest',
      'ursus-knife-scorched',
      'ursus-knife-safari-mesh',
    ],
  },
  {
    slug: 'prisma-case',
    name: 'Prisma Case',
    description: 'Ekte Prisma Case-lineup — samme skins som i det offisielle spillet.',
    imageUrl: 'https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGJKz2lu_XsnXwtmkJjSU91dh8bj35VTqVBP4io_fr3AV6aD8O6BpdKKQVmPEwr1zs-c8Tnngl09w52zTmY2sc3jBag8jXpohE_lK7Ede7E2Kfw',
    casePrice: 500,
    keyPrice: 100,
    skinSlugs: [
      'famas-crypsis',
      'ak-47-uncharted',
      'mac-10-whitefish',
      'galil-ar-akoben',
      'mp7-mischief',
      'p250-verdigris',
      'p90-off-world',
      'awp-atheris',
      'tec-9-bamboozle',
      'desert-eagle-light-rail',
      'mp5-sd-gauss',
      'ump-45-moonrise',
      'r8-revolver-skull-crusher',
      'aug-momentum',
      'xm1014-incinegator',
      'five-seven-angry-mob',
      'm4a4-the-emperor',
      'navaja-knife',
      'navaja-knife-marble-fade',
      'navaja-knife-tiger-tooth',
      'navaja-knife-doppler',
      'navaja-knife-damascus-steel',
      'navaja-knife-ultraviolet',
      'navaja-knife-rust-coat',
      'stiletto-knife',
      'stiletto-knife-marble-fade',
      'stiletto-knife-tiger-tooth',
      'stiletto-knife-doppler',
      'stiletto-knife-damascus-steel',
      'stiletto-knife-ultraviolet',
      'stiletto-knife-rust-coat',
      'talon-knife',
      'talon-knife-marble-fade',
      'talon-knife-tiger-tooth',
      'talon-knife-doppler',
      'talon-knife-damascus-steel',
      'talon-knife-ultraviolet',
      'talon-knife-rust-coat',
      'ursus-knife',
      'ursus-knife-marble-fade',
      'ursus-knife-tiger-tooth',
      'ursus-knife-doppler',
      'ursus-knife-damascus-steel',
      'ursus-knife-ultraviolet',
      'ursus-knife-rust-coat',
    ],
  },
  {
    slug: 'shattered-web-case',
    name: 'Shattered Web Case',
    description: 'Ekte Shattered Web Case-lineup, inkludert Nomad Knife.',
    imageUrl: 'https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGJKz2lu_XsnXwtmkJjSU91dh8bj35VTqVBP4io_fr3EVvKD6MKU_cKPKXWHFxLkls7FsSnDqwUl_sWTczoqheHifbwMmD5F1RvlK7Ec_KL6Q_A',
    casePrice: 500,
    keyPrice: 100,
    skinSlugs: [
      'mp5-sd-acid-wash',
      'nova-plume',
      'g3sg1-black-sand',
      'r8-revolver-memento',
      'dual-berettas-balance',
      'scar-20-torn',
      'm249-warbird',
      'pp-bizon-embargo',
      'ak-47-rat-rod',
      'aug-arctic-wolf',
      'mp7-neon-ply',
      'p2000-obsidian',
      'tec-9-decimator',
      'sg-553-colony-iv',
      'ssg-08-bloodshot',
      'awp-containment-breach',
      'mac-10-stalker',
      'nomad-knife',
      'nomad-knife-fade',
      'nomad-knife-crimson-web',
      'nomad-knife-slaughter',
      'nomad-knife-case-hardened',
      'nomad-knife-urban-masked',
      'nomad-knife-blue-steel',
      'nomad-knife-night-stripe',
      'nomad-knife-stained',
      'nomad-knife-forest-ddpat',
      'nomad-knife-boreal-forest',
      'nomad-knife-scorched',
      'nomad-knife-safari-mesh',
      'paracord-knife',
      'paracord-knife-fade',
      'paracord-knife-crimson-web',
      'paracord-knife-slaughter',
      'paracord-knife-case-hardened',
      'paracord-knife-urban-masked',
      'paracord-knife-blue-steel',
      'paracord-knife-night-stripe',
      'paracord-knife-stained',
      'paracord-knife-forest-ddpat',
      'paracord-knife-boreal-forest',
      'paracord-knife-scorched',
      'paracord-knife-safari-mesh',
      'skeleton-knife',
      'skeleton-knife-fade',
      'skeleton-knife-crimson-web',
      'skeleton-knife-slaughter',
      'skeleton-knife-case-hardened',
      'skeleton-knife-urban-masked',
      'skeleton-knife-blue-steel',
      'skeleton-knife-night-stripe',
      'skeleton-knife-stained',
      'skeleton-knife-forest-ddpat',
      'skeleton-knife-boreal-forest',
      'skeleton-knife-scorched',
      'skeleton-knife-safari-mesh',
      'survival-knife',
      'survival-knife-fade',
      'survival-knife-crimson-web',
      'survival-knife-slaughter',
      'survival-knife-case-hardened',
      'survival-knife-urban-masked',
      'survival-knife-blue-steel',
      'survival-knife-night-stripe',
      'survival-knife-stained',
      'survival-knife-forest-ddpat',
      'survival-knife-boreal-forest',
      'survival-knife-scorched',
      'survival-knife-safari-mesh',
    ],
  },
  {
    slug: 'horizon-case',
    name: 'Horizon Case',
    description: 'Ekte Horizon Case-lineup fra CS2.',
    imageUrl: 'https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGJKz2lu_XsnXwtmkJjSU91dh8bj35VTqVBP4io_fr3IV6vSrbfw8eaiWCjWVkewgseM9TXyxl0wi6mSHn9-tIHqUbg5yDpEmEPlK7EcXFmSLsw',
    casePrice: 500,
    keyPrice: 100,
    skinSlugs: [
      'aug-amber-slipstream',
      'dual-berettas-shred',
      'glock-18-warhawk',
      'mp9-capillary',
      'p90-traction',
      'r8-revolver-survivalist',
      'tec-9-snek-9',
      'cz75-auto-eco',
      'g3sg1-high-seas',
      'nova-toy-soldier',
      'awp-paw',
      'mp7-powercore',
      'm4a1-s-nightmare',
      'sawed-off-devourer',
      'famas-eye-of-athena',
      'ak-47-neon-rider',
      'desert-eagle-code-red',
      'navaja-knife',
      'navaja-knife-fade',
      'navaja-knife-crimson-web',
      'navaja-knife-slaughter',
      'navaja-knife-case-hardened',
      'navaja-knife-urban-masked',
      'navaja-knife-blue-steel',
      'navaja-knife-night-stripe',
      'navaja-knife-stained',
      'navaja-knife-forest-ddpat',
      'navaja-knife-boreal-forest',
      'navaja-knife-scorched',
      'navaja-knife-safari-mesh',
      'stiletto-knife',
      'stiletto-knife-fade',
      'stiletto-knife-crimson-web',
      'stiletto-knife-slaughter',
      'stiletto-knife-case-hardened',
      'stiletto-knife-urban-masked',
      'stiletto-knife-blue-steel',
      'stiletto-knife-night-stripe',
      'stiletto-knife-stained',
      'stiletto-knife-forest-ddpat',
      'stiletto-knife-boreal-forest',
      'stiletto-knife-scorched',
      'stiletto-knife-safari-mesh',
      'talon-knife',
      'talon-knife-fade',
      'talon-knife-crimson-web',
      'talon-knife-slaughter',
      'talon-knife-case-hardened',
      'talon-knife-urban-masked',
      'talon-knife-blue-steel',
      'talon-knife-night-stripe',
      'talon-knife-stained',
      'talon-knife-forest-ddpat',
      'talon-knife-boreal-forest',
      'talon-knife-scorched',
      'talon-knife-safari-mesh',
      'ursus-knife',
      'ursus-knife-fade',
      'ursus-knife-crimson-web',
      'ursus-knife-slaughter',
      'ursus-knife-case-hardened',
      'ursus-knife-urban-masked',
      'ursus-knife-blue-steel',
      'ursus-knife-night-stripe',
      'ursus-knife-stained',
      'ursus-knife-forest-ddpat',
      'ursus-knife-boreal-forest',
      'ursus-knife-scorched',
      'ursus-knife-safari-mesh',
    ],
  },
  {
    slug: 'clutch-case',
    name: 'Clutch Case',
    description: 'Ekte Clutch Case-lineup, inkludert Driver Gloves.',
    imageUrl: 'https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGJKz2lu_XsnXwtmkJjSU91dh8bj35VTqVBP4io_frHsVtqr8a_dsdKTAWDWVxLgjsrAwHSvgwEQk4m-ByYuqIC2eO1VyD5QiR_lK7EcxQQPYQA',
    casePrice: 500,
    keyPrice: 100,
    skinSlugs: [
      'pp-bizon-night-riot',
      'five-seven-flame-test',
      'mp9-black-sand',
      'p2000-urban-hazard',
      'r8-revolver-grip',
      'sg-553-aloha',
      'xm1014-oxide-blaze',
      'glock-18-moonrise',
      'negev-lionfish',
      'nova-wild-six',
      'mag-7-swag-7',
      'ump-45-arctic-wolf',
      'aug-stymphalian',
      'awp-mortis',
      'usp-s-cortex',
      'm4a4-neo-noir',
      'mp7-bloodsport',
      'driver-gloves-imperial-plaid',
      'driver-gloves-king-snake',
      'driver-gloves-racing-green',
      'driver-gloves-overtake',
      'hand-wraps-cobalt-skulls',
      'hand-wraps-overprint',
      'hand-wraps-arboreal',
      'hand-wraps-duct-tape',
      'hydra-gloves-case-hardened',
      'hydra-gloves-emerald',
      'hydra-gloves-rattler',
      'hydra-gloves-mangrove',
      'moto-gloves-pow',
      'moto-gloves-polygon',
      'moto-gloves-turtle',
      'moto-gloves-transport',
      'specialist-gloves-crimson-web',
      'specialist-gloves-mogul',
      'specialist-gloves-fade',
      'specialist-gloves-buckshot',
      'sport-gloves-vice',
      'sport-gloves-amphibious',
      'sport-gloves-omega',
      'sport-gloves-bronze-morph',
    ],
  },
  {
    slug: 'falchion-case',
    name: 'Falchion Case',
    description: 'Ekte Falchion Case-lineup, inkludert Falchion Knife.',
    imageUrl: 'https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGJKz2lu_XsnXwtmkJjSU91dh8bj35VTqVBP4io_fpWwI7Pb-P6Y5dvPEDGSSlrsh57U8HHHiwx5yt2-Dwo7_JSnCOw8oCJF0W6dU5dgrLNA1',
    casePrice: 500,
    keyPrice: 100,
    skinSlugs: [
      'galil-ar-rocket-pop',
      'glock-18-bunsen-burner',
      'nova-ranger',
      'p90-elite-build',
      'ump-45-riot',
      'usp-s-torque',
      'famas-neural-net',
      'm4a4-evil-daimyo',
      'mp9-ruby-poison-dart',
      'negev-loudmouth',
      'p2000-handgun',
      'cz75-auto-yellow-jacket',
      'mp7-nemesis',
      'sg-553-cyrex',
      'ak-47-aquamarine-revenge',
      'awp-hyper-beast',
      'falchion-knife',
      'falchion-knife-fade',
      'falchion-knife-crimson-web',
      'falchion-knife-slaughter',
      'falchion-knife-case-hardened',
      'falchion-knife-urban-masked',
      'falchion-knife-blue-steel',
      'falchion-knife-night',
      'falchion-knife-stained',
      'falchion-knife-forest-ddpat',
      'falchion-knife-boreal-forest',
      'falchion-knife-scorched',
      'falchion-knife-safari-mesh',
    ],
  },
  {
    slug: 'chroma-case',
    name: 'Chroma Case',
    description: 'Ekte Chroma Case-lineup fra 2015, inkludert Karambit og Bayonet.',
    imageUrl: 'https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGJKz2lu_XsnXwtmkJjSU91dh8bj35VTqVBP4io_fq2wP7qr6bqI5cvHDCzfBlbcv57JqF3zrxRkj4W6Dwo34dy6QPQAoC5ZyW6dU5cxvklfG',
    casePrice: 500,
    keyPrice: 100,
    skinSlugs: [
      'glock-18-catacombs',
      'm249-system-lock',
      'mp9-deadly-poison',
      'scar-20-grotto',
      'xm1014-quicksilver',
      'dual-berettas-urban-shock',
      'desert-eagle-naga',
      'mac-10-malachite',
      'sawed-off-serenity',
      'ak-47-cartel',
      'm4a4-dragon-king',
      'p250-muertos',
      'awp-man-o-war',
      'galil-ar-chatterbox',
      'bayonet-marble-fade',
      'bayonet-tiger-tooth',
      'bayonet-doppler',
      'bayonet-damascus-steel',
      'bayonet-ultraviolet',
      'bayonet-rust-coat',
      'flip-knife-marble-fade',
      'flip-knife-tiger-tooth',
      'flip-knife-doppler',
      'flip-knife-damascus-steel',
      'flip-knife-ultraviolet',
      'flip-knife-rust-coat',
      'gut-knife-marble-fade',
      'gut-knife-tiger-tooth',
      'gut-knife-doppler',
      'gut-knife-damascus-steel',
      'gut-knife-ultraviolet',
      'gut-knife-rust-coat',
      'karambit-marble-fade',
      'karambit-tiger-tooth',
      'karambit-doppler',
      'karambit-damascus-steel',
      'karambit-ultraviolet',
      'karambit-rust-coat',
      'm9-bayonet-marble-fade',
      'm9-bayonet-tiger-tooth',
      'm9-bayonet-doppler',
      'm9-bayonet-damascus-steel',
      'm9-bayonet-ultraviolet',
      'm9-bayonet-rust-coat',
    ],
  },
  {
    slug: 'gamma-case',
    name: 'Gamma Case',
    description: 'Ekte Gamma Case-lineup fra 2016, inkludert Karambit og M9 Bayonet.',
    imageUrl: 'https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGJKz2lu_XsnXwtmkJjSU91dh8bj35VTqVBP4io_frHEVtvP5bPZrd6XECmOSxe0v4bRoTnnjwBkitWrRm4yoeX3GagMnCZZ2FPlK7EcEv22BnQ',
    casePrice: 500,
    keyPrice: 100,
    skinSlugs: [
      'five-seven-violent-daimyo',
      'mac-10-carnivore',
      'nova-exo',
      'p250-iron-clad',
      'pp-bizon-harvester',
      'sg-553-aerial',
      'tec-9-ice-cap',
      'aug-aristocrat',
      'awp-phobos',
      'p90-chopper',
      'r8-revolver-reboot',
      'sawed-off-limelight',
      'm4a4-desolate-space',
      'p2000-imperial-dragon',
      'scar-20-bloodsport',
      'glock-18-wasteland-rebel',
      'm4a1-s-mecha-industries',
      'bayonet-gamma-doppler',
      'bayonet-lore',
      'bayonet-autotronic',
      'bayonet-black-laminate',
      'bayonet-freehand',
      'bayonet-bright-water',
      'flip-knife-gamma-doppler',
      'flip-knife-lore',
      'flip-knife-autotronic',
      'flip-knife-black-laminate',
      'flip-knife-freehand',
      'flip-knife-bright-water',
      'gut-knife-gamma-doppler',
      'gut-knife-lore',
      'gut-knife-autotronic',
      'gut-knife-black-laminate',
      'gut-knife-bright-water',
      'gut-knife-freehand',
      'karambit-gamma-doppler',
      'karambit-lore',
      'karambit-autotronic',
      'karambit-black-laminate',
      'karambit-freehand',
      'karambit-bright-water',
      'm9-bayonet-gamma-doppler',
      'm9-bayonet-lore',
      'm9-bayonet-autotronic',
      'm9-bayonet-black-laminate',
      'm9-bayonet-bright-water',
      'm9-bayonet-freehand',
    ],
  },
  {
    slug: 'glove-case',
    name: 'Glove Case',
    description: 'Ekte Glove Case-lineup — den aller første hanske-casen i CS-historien.',
    imageUrl: 'https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGJKz2lu_XsnXwtmkJjSU91dh8bj35VTqVBP4io_frHcVuPaoafU1JqiVWWSVkux15OQ8Giiylk0k5mvTnIqpd3PCaQIhWMYkE_lK7EcNeCKW-w',
    casePrice: 800,
    keyPrice: 150,
    skinSlugs: [
      'cz75-auto-polymer',
      'glock-18-ironwork',
      'mp7-cirrus',
      'galil-ar-black-sand',
      'mp9-sand-scale',
      'mag-7-sonar',
      'p2000-turf',
      'dual-berettas-royal-consorts',
      'g3sg1-stinger',
      'm4a1-s-flashback',
      'nova-gila',
      'usp-s-cyrex',
      'famas-mecha-industries',
      'p90-shallow-grave',
      'sawed-off-wasteland-princess',
      'ssg-08-dragonfire',
      'm4a4-buzz-kill',
      'bloodhound-gloves-snakebite',
      'bloodhound-gloves-bronzed',
      'bloodhound-gloves-charred',
      'bloodhound-gloves-guerrilla',
      'driver-gloves-crimson-weave',
      'driver-gloves-convoy',
      'driver-gloves-lunar-weave',
      'driver-gloves-diamondback',
      'hand-wraps-slaughter',
      'hand-wraps-badlands',
      'hand-wraps-spruce-ddpat',
      'hand-wraps-leather',
      'moto-gloves-cool-mint',
      'moto-gloves-boom',
      'moto-gloves-spearmint',
      'moto-gloves-eclipse',
      'specialist-gloves-crimson-kimono',
      'specialist-gloves-emerald-web',
      'specialist-gloves-forest-ddpat',
      'specialist-gloves-foundation',
      'sport-gloves-superconductor',
      'sport-gloves-hedge-maze',
      'sport-gloves-arid',
      'sport-gloves-pandora-s-box',
    ],
  },
  {
    slug: 'spectrum-case',
    name: 'Spectrum Case',
    description: 'Ekte Spectrum Case-lineup fra 2017, inkludert Butterfly Knife og Bowie Knife.',
    imageUrl: 'https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGJKz2lu_XsnXwtmkJjSU91dh8bj35VTqVBP4io_frHQV7qCra_JscqPGCzLCl78ktuAxHSzmzUh_sjvWzdqoI33CaQF2DscjR_lK7EeF3oM7TA',
    casePrice: 500,
    keyPrice: 100,
    skinSlugs: [
      'pp-bizon-jungle-slipstream',
      'scar-20-blueprint',
      'desert-eagle-oxide-blaze',
      'five-seven-capillary',
      'mp7-akoben',
      'p250-ripple',
      'sawed-off-zander',
      'galil-ar-crimson-tsunami',
      'm249-emerald-poison-dart',
      'mac-10-last-dive',
      'ump-45-scaffold',
      'xm1014-seasons',
      'awp-fever-dream',
      'cz75-auto-xiangliu',
      'm4a1-s-decimator',
      'ak-47-bloodsport',
      'usp-s-neo-noir',
      'bowie-knife-marble-fade',
      'bowie-knife-tiger-tooth',
      'bowie-knife-doppler',
      'bowie-knife-damascus-steel',
      'bowie-knife-ultraviolet',
      'bowie-knife-rust-coat',
      'butterfly-knife-marble-fade',
      'butterfly-knife-tiger-tooth',
      'butterfly-knife-doppler',
      'butterfly-knife-damascus-steel',
      'butterfly-knife-ultraviolet',
      'butterfly-knife-rust-coat',
      'falchion-knife-marble-fade',
      'falchion-knife-tiger-tooth',
      'falchion-knife-doppler',
      'falchion-knife-damascus-steel',
      'falchion-knife-ultraviolet',
      'falchion-knife-rust-coat',
      'huntsman-knife-marble-fade',
      'huntsman-knife-tiger-tooth',
      'huntsman-knife-doppler',
      'huntsman-knife-damascus-steel',
      'huntsman-knife-ultraviolet',
      'huntsman-knife-rust-coat',
      'shadow-daggers-marble-fade',
      'shadow-daggers-tiger-tooth',
      'shadow-daggers-doppler',
      'shadow-daggers-damascus-steel',
      'shadow-daggers-ultraviolet',
      'shadow-daggers-rust-coat',
    ],
  },
  {
    slug: 'operation-hydra-case',
    name: 'Operation Hydra Case',
    description: 'Ekte Operation Hydra Case-lineup, inkludert Sport Gloves.',
    imageUrl: 'https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGJKz2lu_XsnXwtmkJjSU91dh8bj35VTqVBP4io_frHUVt_b6PfY1JfOSXDXJxbgjtLFqHnDqx0Qmtm_Vzdf4ICmUZlJ2C5F2TPlK7EdjN0FcPg',
    casePrice: 800,
    keyPrice: 150,
    skinSlugs: [
      'usp-s-blueprint',
      'famas-macabre',
      'm4a1-s-briefing',
      'mac-10-aloha',
      'mag-7-hard-water',
      'tec-9-cut-out',
      'ump-45-metal-flowers',
      'ak-47-orbit-mk01',
      'p2000-woodsman',
      'p250-red-rock',
      'p90-death-grip',
      'ssg-08-death-s-head',
      'dual-berettas-cobra-strike',
      'galil-ar-sugar-rush',
      'm4a4-hellfire',
      'five-seven-hyper-beast',
      'awp-oni-taiji',
      'bloodhound-gloves-snakebite',
      'bloodhound-gloves-bronzed',
      'bloodhound-gloves-charred',
      'bloodhound-gloves-guerrilla',
      'driver-gloves-crimson-weave',
      'driver-gloves-convoy',
      'driver-gloves-lunar-weave',
      'driver-gloves-diamondback',
      'hand-wraps-slaughter',
      'hand-wraps-badlands',
      'hand-wraps-spruce-ddpat',
      'hand-wraps-leather',
      'moto-gloves-cool-mint',
      'moto-gloves-boom',
      'moto-gloves-spearmint',
      'moto-gloves-eclipse',
      'specialist-gloves-crimson-kimono',
      'specialist-gloves-emerald-web',
      'specialist-gloves-forest-ddpat',
      'specialist-gloves-foundation',
      'sport-gloves-superconductor',
      'sport-gloves-hedge-maze',
      'sport-gloves-arid',
      'sport-gloves-pandora-s-box',
    ],
  },
  {
    slug: 'prisma-2-case',
    name: 'Prisma 2 Case',
    description: 'Ekte Prisma 2 Case-lineup — oppfølgeren til Prisma Case, inkludert Ursus Knife.',
    imageUrl: 'https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGJKz2lu_XsnXwtmkJjSU91dh8bj35VTqVBP4io_fr3cV6vT9avBvefWWDDGTxbZ14rhsTX7qkE90sDiHwt2pdC-TblJ2DsB1QPlK7Ee9riHKAA',
    casePrice: 500,
    keyPrice: 100,
    skinSlugs: [
      'aug-tom-cat',
      'awp-capillary',
      'cz75-auto-distressed',
      'desert-eagle-blue-ply',
      'mp5-sd-desert-strike',
      'negev-prototype',
      'r8-revolver-bone-forged',
      'p2000-acid-etched',
      'sawed-off-apocalypto',
      'scar-20-enforcer',
      'sg-553-darkwing',
      'ssg-08-fever-dream',
      'ak-47-phantom-disruptor',
      'mac-10-disco-tech',
      'mag-7-justice',
      'm4a1-s-player-two',
      'glock-18-bullet-queen',
      'navaja-knife',
      'navaja-knife-marble-fade',
      'navaja-knife-tiger-tooth',
      'navaja-knife-doppler',
      'navaja-knife-damascus-steel',
      'navaja-knife-ultraviolet',
      'navaja-knife-rust-coat',
      'stiletto-knife',
      'stiletto-knife-marble-fade',
      'stiletto-knife-tiger-tooth',
      'stiletto-knife-doppler',
      'stiletto-knife-damascus-steel',
      'stiletto-knife-ultraviolet',
      'stiletto-knife-rust-coat',
      'talon-knife',
      'talon-knife-marble-fade',
      'talon-knife-tiger-tooth',
      'talon-knife-doppler',
      'talon-knife-damascus-steel',
      'talon-knife-ultraviolet',
      'talon-knife-rust-coat',
      'ursus-knife',
      'ursus-knife-marble-fade',
      'ursus-knife-tiger-tooth',
      'ursus-knife-doppler',
      'ursus-knife-damascus-steel',
      'ursus-knife-ultraviolet',
      'ursus-knife-rust-coat',
    ],
  },
  {
    slug: 'fracture-case',
    name: 'Fracture Case',
    description: 'Ekte Fracture Case-lineup fra 2020, inkludert Nomad og Paracord Knife.',
    imageUrl: 'https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGJKz2lu_XsnXwtmkJjSU91dh8bj35VTqVBP4io_fr3QV7aD7OP01IfbGDzPCmbsm4LU5GnvkzUsi4WvUmIqtci_CPQNyApsjE_lK7EfrhW545A',
    casePrice: 500,
    keyPrice: 100,
    skinSlugs: [
      'negev-ultralight',
      'p2000-gnarled',
      'sg-553-ol-rusty',
      'ssg-08-mainframe-001',
      'p250-cassette',
      'p90-freight',
      'pp-bizon-runic',
      'mag-7-monster-call',
      'tec-9-brother',
      'mac-10-allure',
      'galil-ar-connexion',
      'mp5-sd-kitbash',
      'm4a4-tooth-fairy',
      'glock-18-vogue',
      'xm1014-entombed',
      'desert-eagle-printstream',
      'ak-47-legion-of-anubis',
      'nomad-knife',
      'nomad-knife-fade',
      'nomad-knife-crimson-web',
      'nomad-knife-slaughter',
      'nomad-knife-case-hardened',
      'nomad-knife-urban-masked',
      'nomad-knife-blue-steel',
      'nomad-knife-night-stripe',
      'nomad-knife-stained',
      'nomad-knife-forest-ddpat',
      'nomad-knife-boreal-forest',
      'nomad-knife-scorched',
      'nomad-knife-safari-mesh',
      'paracord-knife',
      'paracord-knife-fade',
      'paracord-knife-crimson-web',
      'paracord-knife-slaughter',
      'paracord-knife-case-hardened',
      'paracord-knife-urban-masked',
      'paracord-knife-blue-steel',
      'paracord-knife-night-stripe',
      'paracord-knife-stained',
      'paracord-knife-forest-ddpat',
      'paracord-knife-boreal-forest',
      'paracord-knife-scorched',
      'paracord-knife-safari-mesh',
      'skeleton-knife',
      'skeleton-knife-fade',
      'skeleton-knife-crimson-web',
      'skeleton-knife-slaughter',
      'skeleton-knife-case-hardened',
      'skeleton-knife-urban-masked',
      'skeleton-knife-blue-steel',
      'skeleton-knife-night-stripe',
      'skeleton-knife-stained',
      'skeleton-knife-forest-ddpat',
      'skeleton-knife-boreal-forest',
      'skeleton-knife-scorched',
      'skeleton-knife-safari-mesh',
      'survival-knife',
      'survival-knife-fade',
      'survival-knife-crimson-web',
      'survival-knife-slaughter',
      'survival-knife-case-hardened',
      'survival-knife-urban-masked',
      'survival-knife-blue-steel',
      'survival-knife-night-stripe',
      'survival-knife-stained',
      'survival-knife-forest-ddpat',
      'survival-knife-boreal-forest',
      'survival-knife-scorched',
      'survival-knife-safari-mesh',
    ],
  },
  {
    slug: 'operation-broken-fang-case',
    name: 'Operation Broken Fang Case',
    description: 'Ekte Operation Broken Fang Case-lineup, inkludert Broken Fang Gloves.',
    imageUrl: 'https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGJKz2lu_XsnXwtmkJjSU91dh8bj35VTqVBP4io_fr3UVu6P-MPQ0dKbCVzLGx7wgtbM6S3jhw0V25m-EnNj7JS7GaQ4nD8QiRflK7EfH0YGFHg',
    casePrice: 800,
    keyPrice: 150,
    skinSlugs: [
      'cz75-auto-vendetta',
      'p90-cocoa-rampage',
      'g3sg1-digital-mesh',
      'galil-ar-vandal',
      'p250-contaminant',
      'm249-deep-relief',
      'mp5-sd-condition-zero',
      'awp-exoskeleton',
      'dual-berettas-dezastre',
      'nova-clear-polymer',
      'ssg-08-parallax',
      'ump-45-gold-bismuth',
      'five-seven-fairy-tale',
      'm4a4-cyber-security',
      'usp-s-monster-mashup',
      'm4a1-s-printstream',
      'glock-18-neo-noir',
      'broken-fang-gloves-yellow-banded',
      'broken-fang-gloves-unhinged',
      'broken-fang-gloves-needle-point',
      'broken-fang-gloves-jade',
      'driver-gloves-snow-leopard',
      'driver-gloves-black-tie',
      'driver-gloves-rezan-the-red',
      'driver-gloves-queen-jaguar',
      'hand-wraps-caution',
      'hand-wraps-giraffe',
      'hand-wraps-constrictor',
      'hand-wraps-desert-shamagh',
      'moto-gloves-blood-pressure',
      'moto-gloves-smoke-out',
      'moto-gloves-finish-line',
      'moto-gloves-3rd-commando-company',
      'specialist-gloves-field-agent',
      'specialist-gloves-tiger-strike',
      'specialist-gloves-lt-commander',
      'specialist-gloves-marble-fade',
      'sport-gloves-slingshot',
      'sport-gloves-scarlet-shamagh',
      'sport-gloves-nocts',
      'sport-gloves-big-game',
    ],
  },
  {
    slug: 'snakebite-case',
    name: 'Snakebite Case',
    description: 'Ekte Snakebite Case-lineup fra 2021.',
    imageUrl: 'https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGJKz2lu_XsnXwtmkJjSU91dh8bj35VTqVBP4io_fr3oVvvT4bfI4dvTLCGTCmLl16ec7TX_mk08k42iHwtqscy-WPVUmCZJ4R_lK7Ed8Q6OYtw',
    casePrice: 800,
    keyPrice: 150,
    skinSlugs: [
      'sg-553-heavy-metal',
      'glock-18-clear-polymer',
      'm249-o-s-i-p-r',
      'cz75-auto-circaetus',
      'ump-45-oscillator',
      'r8-revolver-junk-yard',
      'nova-windblown',
      'p250-cyber-shell',
      'negev-dev-texture',
      'mac-10-button-masher',
      'desert-eagle-trigger-discipline',
      'ak-47-slate',
      'mp9-food-chain',
      'xm1014-xoxo',
      'galil-ar-chromatic-aberration',
      'usp-s-the-traitor',
      'm4a4-in-living-color',
      'broken-fang-gloves-yellow-banded',
      'broken-fang-gloves-unhinged',
      'broken-fang-gloves-needle-point',
      'broken-fang-gloves-jade',
      'driver-gloves-snow-leopard',
      'driver-gloves-black-tie',
      'driver-gloves-rezan-the-red',
      'driver-gloves-queen-jaguar',
      'hand-wraps-caution',
      'hand-wraps-giraffe',
      'hand-wraps-constrictor',
      'hand-wraps-desert-shamagh',
      'moto-gloves-blood-pressure',
      'moto-gloves-smoke-out',
      'moto-gloves-finish-line',
      'moto-gloves-3rd-commando-company',
      'specialist-gloves-field-agent',
      'specialist-gloves-tiger-strike',
      'specialist-gloves-lt-commander',
      'specialist-gloves-marble-fade',
      'sport-gloves-slingshot',
      'sport-gloves-scarlet-shamagh',
      'sport-gloves-nocts',
      'sport-gloves-big-game',
    ],
  },
  {
    slug: 'operation-riptide-case',
    name: 'Operation Riptide Case',
    description: 'Ekte Operation Riptide Case-lineup, inkludert Butterfly Knife.',
    imageUrl: 'https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGJKz2lu_XsnXwtmkJjSU91dh8bj35VTqVBP4io_fr3sVtvD2O_Q9dqfEXTWSlepz4bA5THnikx915z6BytmuIHiXaAdyDpEhTflK7EdW-TaRMg',
    casePrice: 500,
    keyPrice: 100,
    skinSlugs: [
      'aug-plague',
      'dual-berettas-tread',
      'g3sg1-keeping-tabs',
      'mp7-guerrilla',
      'pp-bizon-lumen',
      'usp-s-black-lotus',
      'xm1014-watchdog',
      'mag-7-bi83-spectrum',
      'famas-zx-spectron',
      'five-seven-boost-protocol',
      'mp9-mount-fuji',
      'm4a4-spider-lily',
      'mac-10-toybox',
      'glock-18-snack-attack',
      'ssg-08-turbo-peek',
      'ak-47-leet-museo',
      'desert-eagle-ocean-drive',
      'bowie-knife-gamma-doppler',
      'bowie-knife-lore',
      'bowie-knife-autotronic',
      'bowie-knife-black-laminate',
      'bowie-knife-freehand',
      'bowie-knife-bright-water',
      'butterfly-knife-gamma-doppler',
      'butterfly-knife-lore',
      'butterfly-knife-autotronic',
      'butterfly-knife-black-laminate',
      'butterfly-knife-freehand',
      'butterfly-knife-bright-water',
      'falchion-knife-gamma-doppler',
      'falchion-knife-lore',
      'falchion-knife-autotronic',
      'falchion-knife-black-laminate',
      'falchion-knife-freehand',
      'falchion-knife-bright-water',
      'huntsman-knife-gamma-doppler',
      'huntsman-knife-lore',
      'huntsman-knife-autotronic',
      'huntsman-knife-black-laminate',
      'huntsman-knife-freehand',
      'huntsman-knife-bright-water',
      'shadow-daggers-gamma-doppler',
      'shadow-daggers-lore',
      'shadow-daggers-autotronic',
      'shadow-daggers-black-laminate',
      'shadow-daggers-freehand',
      'shadow-daggers-bright-water',
    ],
  },
  {
    slug: 'dreams-nightmares-case',
    name: 'Dreams & Nightmares Case',
    description: 'Ekte Dreams & Nightmares Case-lineup fra 2021.',
    imageUrl: 'https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGJKz2lu_XsnXwtmkJjSU91dh8bj35VTqVBP4io_frnIV7Kb5OaU-JqfHDzXFle0u4LY8Gy_kkRgisGzcm4v4J3vDOAQmDMdyRvlK7EcmeCU3yw',
    casePrice: 500,
    keyPrice: 100,
    skinSlugs: [
      'five-seven-scrawl',
      'mac-10-ensnared',
      'mag-7-foresight',
      'mp5-sd-necro-jr',
      'p2000-lifted-spirits',
      'scar-20-poultrygeist',
      'sawed-off-spirit-board',
      'pp-bizon-space-cat',
      'g3sg1-dream-glade',
      'm4a1-s-night-terror',
      'xm1014-zombie-offensive',
      'usp-s-ticket-to-hell',
      'dual-berettas-melondrama',
      'famas-rapid-eye-movement',
      'mp7-abyssal-apparition',
      'ak-47-nightwish',
      'mp9-starlight-protector',
      'bowie-knife-gamma-doppler',
      'bowie-knife-lore',
      'bowie-knife-autotronic',
      'bowie-knife-black-laminate',
      'bowie-knife-freehand',
      'bowie-knife-bright-water',
      'butterfly-knife-gamma-doppler',
      'butterfly-knife-lore',
      'butterfly-knife-autotronic',
      'butterfly-knife-black-laminate',
      'butterfly-knife-freehand',
      'butterfly-knife-bright-water',
      'falchion-knife-gamma-doppler',
      'falchion-knife-lore',
      'falchion-knife-autotronic',
      'falchion-knife-black-laminate',
      'falchion-knife-freehand',
      'falchion-knife-bright-water',
      'huntsman-knife-gamma-doppler',
      'huntsman-knife-lore',
      'huntsman-knife-autotronic',
      'huntsman-knife-black-laminate',
      'huntsman-knife-freehand',
      'huntsman-knife-bright-water',
      'shadow-daggers-gamma-doppler',
      'shadow-daggers-lore',
      'shadow-daggers-autotronic',
      'shadow-daggers-black-laminate',
      'shadow-daggers-freehand',
      'shadow-daggers-bright-water',
    ],
  },
  {
    slug: 'recoil-case',
    name: 'Recoil Case',
    description: 'Ekte Recoil Case-lineup fra 2022.',
    imageUrl: 'https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGJKz2lu_XsnXwtmkJjSU91dh8bj35VTqVBP4io_frnMVu6b-avA-JqSSCjSWwuhz47U9TCzlxh9yt2WGnNqgIi-fbgUkWMNxFPlK7EdIJF6a2Q',
    casePrice: 800,
    keyPrice: 150,
    skinSlugs: [
      'famas-meow-36',
      'galil-ar-destroyer',
      'm4a4-poly-mag',
      'mac-10-monkeyflage',
      'negev-drop-me',
      'ump-45-roadblock',
      'glock-18-winterized',
      'r8-revolver-crazy-8',
      'm249-downtown',
      'sg-553-dragon-tech',
      'p90-vent-rush',
      'dual-berettas-flora-carnivora',
      'ak-47-ice-coaled',
      'p250-visions',
      'sawed-off-kiss-love',
      'usp-s-printstream',
      'awp-chromatic-aberration',
      'broken-fang-gloves-yellow-banded',
      'broken-fang-gloves-unhinged',
      'broken-fang-gloves-needle-point',
      'broken-fang-gloves-jade',
      'driver-gloves-snow-leopard',
      'driver-gloves-black-tie',
      'driver-gloves-rezan-the-red',
      'driver-gloves-queen-jaguar',
      'hand-wraps-caution',
      'hand-wraps-giraffe',
      'hand-wraps-constrictor',
      'hand-wraps-desert-shamagh',
      'moto-gloves-blood-pressure',
      'moto-gloves-smoke-out',
      'moto-gloves-finish-line',
      'moto-gloves-3rd-commando-company',
      'specialist-gloves-field-agent',
      'specialist-gloves-tiger-strike',
      'specialist-gloves-lt-commander',
      'specialist-gloves-marble-fade',
      'sport-gloves-slingshot',
      'sport-gloves-scarlet-shamagh',
      'sport-gloves-nocts',
      'sport-gloves-big-game',
    ],
  },
  {
    slug: 'revolution-case',
    name: 'Revolution Case',
    description: 'Ekte Revolution Case-lineup, inkludert Hydra Gloves.',
    imageUrl: 'https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGJKz2lu_XsnXwtmkJjSU91dh8bj35VTqVBP4io_frnAVvfb6aqduc_TFVjTCxbx05OU4S3jilE9w4DzRnImtIy2Sa1JzDJEhRPlK7EcO4U8gfA',
    casePrice: 800,
    keyPrice: 150,
    skinSlugs: [
      'mag-7-insomnia',
      'mp9-featherweight',
      'scar-20-fragments',
      'p250-re-built',
      'mp5-sd-liquidation',
      'sg-553-cyberforce',
      'tec-9-rebel',
      'm4a1-s-emphorosaur-s',
      'glock-18-umbral-rabbit',
      'mac-10-sakkaku',
      'r8-revolver-banana-cannon',
      'p90-neoqueen',
      'awp-duality',
      'ump-45-wild-child',
      'p2000-wicked-sick',
      'm4a4-temukau',
      'ak-47-head-shot',
      'driver-gloves-imperial-plaid',
      'driver-gloves-king-snake',
      'driver-gloves-racing-green',
      'driver-gloves-overtake',
      'hand-wraps-cobalt-skulls',
      'hand-wraps-overprint',
      'hand-wraps-arboreal',
      'hand-wraps-duct-tape',
      'hydra-gloves-case-hardened',
      'hydra-gloves-emerald',
      'hydra-gloves-rattler',
      'hydra-gloves-mangrove',
      'moto-gloves-pow',
      'moto-gloves-polygon',
      'moto-gloves-turtle',
      'moto-gloves-transport',
      'specialist-gloves-crimson-web',
      'specialist-gloves-mogul',
      'specialist-gloves-fade',
      'specialist-gloves-buckshot',
      'sport-gloves-vice',
      'sport-gloves-amphibious',
      'sport-gloves-omega',
      'sport-gloves-bronze-morph',
    ],
  },
  {
    slug: 'kilowatt-case',
    name: 'Kilowatt Case',
    description: 'Ekte Kilowatt Case-lineup fra 2024, inkludert Kukri Knife.',
    imageUrl: 'https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGJKz2lu_XsnXwtmkJjSU91dh8bj35VTqVBP4io_frnEVvqf_a6VoIfGSXz7Hlbwg57QwSS_mxhl15jiGyN37c3_GZw91W8BwRflK7EfKsa2sfw',
    casePrice: 500,
    keyPrice: 100,
    skinSlugs: [
      'dual-berettas-hideout',
      'mac-10-light-box',
      'nova-dark-sigil',
      'ssg-08-dezastre',
      'tec-9-slag',
      'ump-45-motorized',
      'xm1014-irezumi',
      'glock-18-block-18',
      'm4a4-etch-lord',
      'five-seven-hybrid',
      'mp7-just-smile',
      'sawed-off-analog-input',
      'm4a1-s-black-lotus',
      'zeus-x27-olympus',
      'usp-s-jawbreaker',
      'awp-chrome-cannon',
      'ak-47-inheritance',
      'kukri-knife',
      'kukri-knife-fade',
      'kukri-knife-slaughter',
      'kukri-knife-blue-steel',
      'kukri-knife-stained',
      'kukri-knife-case-hardened',
      'kukri-knife-forest-ddpat',
      'kukri-knife-boreal-forest',
      'kukri-knife-crimson-web',
      'kukri-knife-scorched',
      'kukri-knife-safari-mesh',
      'kukri-knife-night-stripe',
      'kukri-knife-urban-masked',
    ],
  },
  {
    slug: 'fever-case',
    name: 'Fever Case',
    description: 'Ekte Fever Case-lineup — den nyeste casen i samlingen.',
    imageUrl: 'https://community.akamai.steamstatic.com/economy/image/i0CoZ81Ui0m-9KwlBY1L_18myuGuq1wfhWSaZgMttyVfPaERSR0Wqmu7LAocGJKz2lu_XsnXwtmkJjSU91dh8bj35VTqVBP4io_frncVtqv7MPE8JaHHCj_Dl-wk4-NtFirikURy4jiGwo2udHqVaAEjDZp3EflK7EeSMnMs4w',
    casePrice: 500,
    keyPrice: 100,
    skinSlugs: [
      'm4a4-choppa',
      'mag-7-resupply',
      'ssg-08-memorial',
      'p2000-sure-grip',
      'usp-s-pc-grn',
      'mp9-nexus',
      'xm1014-mockingbird',
      'desert-eagle-serpent-strike',
      'zeus-x27-tosai',
      'nova-rising-sun',
      'galil-ar-control',
      'p90-wave-breaker',
      'ak-47-searing-rage',
      'glock-18-shinobu',
      'ump-45-k-o-factory',
      'famas-bad-trip',
      'awp-printstream',
      'survival-knife',
      'survival-knife-marble-fade',
      'survival-knife-tiger-tooth',
      'survival-knife-doppler',
      'survival-knife-damascus-steel',
      'survival-knife-ultraviolet',
      'survival-knife-rust-coat',
      'skeleton-knife',
      'skeleton-knife-marble-fade',
      'skeleton-knife-tiger-tooth',
      'skeleton-knife-doppler',
      'skeleton-knife-damascus-steel',
      'skeleton-knife-ultraviolet',
      'skeleton-knife-rust-coat',
      'paracord-knife',
      'paracord-knife-marble-fade',
      'paracord-knife-tiger-tooth',
      'paracord-knife-doppler',
      'paracord-knife-damascus-steel',
      'paracord-knife-ultraviolet',
      'paracord-knife-rust-coat',
      'nomad-knife',
      'nomad-knife-marble-fade',
      'nomad-knife-tiger-tooth',
      'nomad-knife-doppler',
      'nomad-knife-damascus-steel',
      'nomad-knife-ultraviolet',
      'nomad-knife-rust-coat',
    ],
  },
]
